{{- if index .Values "eric-cnom-server" "enabled" }}
{{- if .Values.global -}}
{{- if .Values.global.networkPolicy -}}
{{- if .Values.global.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "eric-cn-app-mgmt-integration.name" . }}-eric-cnom-server
  labels:
    {{- include "eric-cn-app-mgmt-integration.labels" . | nindent 4 }}
  annotations:
    {{- include "eric-cn-app-mgmt-integration.product-info" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: eric-cnom-server
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: eric-cnom-server
{{- end }}
{{- end }}
{{- end }}
{{- end }}
