{{ if index .Values "eric-lcm-container-registry" "enabled" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "eric-cn-app-mgmt-integration.lcmregistry" . }}
  labels:
    {{- include "eric-cn-app-mgmt-integration.labels" . | nindent 4 }}
  annotations:
    {{- include "eric-cn-app-mgmt-integration.product-info" . | nindent 4 }}
type: Opaque
data:
  htpasswd: {{ include "eric-cn-app-mgmt-integration.lcmregistrycred" . | b64enc | quote  }}
{{- end -}}
