{{ if and ( index .Values "eric-lcm-helm-chart-registry" "enabled" ) ( eq (index .Values "eric-lcm-helm-chart-registry" "ingress" "generateSelfSignedCerts") true ) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "eric-cn-app-mgmt-integration.lcmTlsSecretHelmChartRegistry" . }}
  labels:
    {{- include "eric-cn-app-mgmt-integration.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,post-delete
    {{- include "eric-cn-app-mgmt-integration.product-info" . | nindent 4 }}
type: kubernetes.io/tls
data:
  {{ include "eric-cn-app-mgmt-integration.gen-helm-chart-registry-certs" . | nindent 2 }}
{{- end -}}
