apiVersion: v1
kind: Secret
metadata:
  name: {{ include "eric-cn-app-mgmt-integration.executor-container-creds" . }}
  labels:
    {{- include "eric-cn-app-mgmt-integration.labels" . | nindent 4 }}
  annotations:
    {{- include "eric-cn-app-mgmt-integration.product-info" . | nindent 4 }}
type: Opaque
data:
  container_cred_id: {{ .Values.global.extraEnv.container_cred_id | b64enc }}
  container_cred_pass: {{ .Values.global.extraEnv.container_cred_pass | b64enc }}
