apiVersion: v1
kind: Secret
metadata:
  name: {{ include "eric-cn-app-mgmt-integration.MinioSecretName" . }}
  labels:
    {{- include "eric-cn-app-mgmt-integration.labels" . | nindent 4 }}
  annotations:
    {{- include "eric-cn-app-mgmt-integration.product-info" . | nindent 4 }}
type: Opaque
data:
  accesskey: {{ randAlphaNum 20 | b64enc | quote }}
  secretkey: {{ randAlphaNum 40 | b64enc | quote }}
